# Generated by Django 3.2.15 on 2022-08-13 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Learn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presence', models.BooleanField()),
                ('date', models.DateField(blank=True, default='2020-10-10', null=True)),
                ('attention', models.IntegerField(blank=True, choices=[(1, 'Bad'), (2, 'Medieum'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')])),
                ('behavior', models.IntegerField(blank=True, choices=[(1, 'Bad'), (2, 'Medieum'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')])),
                ('interaction', models.IntegerField(blank=True, choices=[(1, 'Bad'), (2, 'Medieum'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')])),
                ('communiction_skills', models.IntegerField(blank=True, choices=[(1, 'Bad'), (2, 'Medieum'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')])),
                ('leadership_skills', models.IntegerField(blank=True, choices=[(1, 'Bad'), (2, 'Medieum'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')])),
                ('team_skills', models.IntegerField(blank=True, choices=[(1, 'Bad'), (2, 'Medieum'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')])),
                ('logical_thinking', models.IntegerField(blank=True, choices=[(1, 'Bad'), (2, 'Medieum'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')])),
                ('critical_thinking', models.IntegerField(blank=True, choices=[(1, 'Bad'), (2, 'Medieum'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')])),
                ('creative_thinking', models.IntegerField(blank=True, choices=[(1, 'Bad'), (2, 'Medieum'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')])),
                ('proplem_solving', models.IntegerField(blank=True, choices=[(1, 'Bad'), (2, 'Medieum'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')])),
                ('nots', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('mid_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('login_id', models.CharField(default='a', max_length=50)),
                ('address', models.CharField(max_length=250)),
                ('birth_date', models.DateField()),
                ('phone', models.IntegerField()),
                ('class_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=50)),
                ('class_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Teach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification', models.CharField(blank=True, max_length=30)),
                ('rate_students', models.ManyToManyField(through='data.Rate', to='data.Student')),
                ('teacher_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('teaching', models.ManyToManyField(through='data.Teach', to='data.Subject')),
            ],
        ),
        migrations.AddField(
            model_name='teach',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.teacher'),
        ),
        migrations.AddField(
            model_name='student',
            name='Subjects',
            field=models.ManyToManyField(through='data.Learn', to='data.Subject'),
        ),
        migrations.AddField(
            model_name='rate',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.student'),
        ),
        migrations.AddField(
            model_name='rate',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data.subject'),
        ),
        migrations.AddField(
            model_name='rate',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.teacher'),
        ),
        migrations.AddField(
            model_name='learn',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.student'),
        ),
        migrations.AddField(
            model_name='learn',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.subject'),
        ),
        migrations.CreateModel(
            name='Documintation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body_text', models.CharField(max_length=255)),
                ('file_body', models.FileField(upload_to='files')),
                ('date', models.DateField()),
                ('teacher_publish_it', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Declirations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=5000)),
                ('body_text', models.TextField()),
                ('date', models.DateField()),
                ('teacher_publish_it', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.teacher')),
            ],
        ),
    ]
