# Generated by Django 4.0.4 on 2022-05-13 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='bearth_date',
            new_name='birth_date',
        ),
    ]
