# Generated by Django 4.0.4 on 2022-06-03 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_learn_rate_subject_teacher_teach_rate_teacher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='first_name',
        ),
    ]
