# Generated by Django 4.0.4 on 2022-06-03 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_remove_teacher_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='last_name',
        ),
    ]
