# Generated by Django 4.0.4 on 2022-06-03 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_remove_teacher_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='mid_name',
        ),
    ]
