# Generated by Django 4.0.4 on 2022-06-05 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_remove_teacher_mid_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='date',
            field=models.DateField(blank=True, default='Some String', null=True),
        ),
    ]
