# Generated by Django 4.0.4 on 2022-06-05 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_rate_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='date',
            field=models.DateField(blank=True, default='2020-10-10', null=True),
        ),
    ]
