# Generated by Django 4.0.4 on 2022-06-21 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_alter_rate_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='is_manager',
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='declirations',
            name='title',
            field=models.CharField(max_length=5000),
        ),
    ]
