# Generated by Django 4.0.4 on 2022-06-21 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_remove_teacher_is_manager_teacher_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teaching',
            field=models.ManyToManyField(through='data.Teach', to='data.subject'),
        ),
    ]
