# Generated by Django 4.0.4 on 2022-07-08 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_teacher_teaching'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data.subject'),
        ),
    ]
