# Generated by Django 4.0.4 on 2022-07-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_rate_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='login_id',
            field=models.CharField(default='a', max_length=50),
        ),
    ]
