# Generated by Django 4.0.4 on 2022-08-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_alter_rate_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declirations',
            name='body_img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
