# Generated by Django 4.0.4 on 2022-05-06 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('mid_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=250)),
                ('bearth_date', models.DateField()),
                ('phone', models.IntegerField()),
                ('class_num', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='d',
        ),
    ]
